config/routes.rb
Rails.application.routes.draw do

  get 'videos/upload'

  resources :categories
  resources :carts, only: [:index]
  post '/payment' => 'carts#payment'
  resources :order_items, only: [:create, :update, :destroy]

  post '/rate' => 'rater#create', :as => 'rate'
  mount ActionCable.server => '/cable'

  root "home#index"

  post 'videos/upload'

  get ':username/follow_user', to: 'relationships#follow_user', as: :follow_user
  get ':username/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get '/dashboard' => 'dashboard#show', as: :dashboard

  post '/stores/:id' => 'stores#show', as: :start_streaming
  post '/stores/:id/end' => 'stores#show', as: :stop_streaming

  resources :stores, only: [:show, :edit, :update] do
    resources :products
  end

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users, only: [:create]
  get ':username' =>  'users#show'

  # DEVELOPMENT ONLY: sketches are html/css/js layouts with no logic yet,
  # the code can be reused elsewhere when backend ready
  get 'sketches/store' => 'sketches#store'
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, :presence => true
  validates_with AttachmentPresenceValidator, attributes: :avatar

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/follow.rb
class Follow < ApplicationRecord

  belongs_to :follower, foreign_key: 'follower_id', class_name: 'User'
  belongs_to :following, foreign_key: 'following_id', class_name: 'User'

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :store
  belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  has_many :order_items

  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

  private

  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:total] = subtotal
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end


  def total_price
    unit_price * quantity
  end

  private

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store
  belongs_to :category
  has_many :order_items

  validates :price, :presence => true
  validates :name, :presence => true
  validates :description, :presence => true
  validates :image, attachment_presence: true
  validates_with AttachmentPresenceValidator, attributes: :image

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user

  has_many :products, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_one :stream_instance

  extend FriendlyId
  friendly_id :name, use: :slugged

  ratyrate_rateable "quality"

  validates :name, presence: true, uniqueness: { message: "Username already in use" }
  validates :slug, presence: true, uniqueness: { message: "Username already in use" }

  #image stuff
  has_attached_file :cover_photo, styles: { large: "800x800>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :cover_photo, content_type: /\Aimage\/.*\z/

end

app/models/stream_instance.rb
class StreamInstance < ApplicationRecord
  belongs_to :store
end

app/models/user.rb
class User < ApplicationRecord

  has_one :store, dependent: :destroy
  has_many :messages, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,  :omniauthable, :omniauth_providers => [:facebook]

  # Config paperclip
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  # Config subscribe
  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following

  # Config ratyrate for rating
  ratyrate_rater

  # Actions
  after_create :generate_empty_store
  after_update :update_store_slug

  def follow(user_id)
    following_relationships.create(following_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.find_by(following_id: user_id).destroy
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.name.delete(' ')   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end


  private

    def generate_empty_store
      store = Store.create!(user_id: self.id, name: self.username)
      StreamInstance.create!(store_id: store.id)
    end

  def update_store_slug
    self.store.update(name: self.username, slug: nil)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    unless current_user
      flash[:error] = "You must login to view Dashboard"
      redirect_to user_session_path
    else
      @user = current_user
      @categories = Category.all
      non_empty_stores = Store.joins(:products).group('stores.id')

      @stores = non_empty_stores.where.not(user_id: @user.id)
      @streaming_stores = Store.where.not(user_id: @user.id, streaming_now: false)

      my_follows = Follow.where(follower_id: @user.id)
      my_followed_users = User.find(my_follows.map(&:following_id))
      @subscribed_stores = []
      my_followed_users.each do |user|
        @subscribed_stores.push(user.store)
      end

      #other stores which are not in the first two lists
      @other_stores = @stores - (@subscribed_stores + @streaming_stores)


      #for seller dashboard
      @available_products = current_user.store.products
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/dashboard/_buyer_dash.html.erb
<div id="buyer_dash" role="tabpanel" class="tab-pane fade show active">
  <div class="container">
    <h2>Stores streaming now</h2>
    <div class="row">
      <% if @streaming_stores.count > 0 %>
          <% @streaming_stores.each do |store| %>
              <%= render partial: 'stores/store_listing', locals: {store: store} %>
          <% end %>
      <% else %>
          <p style="margin-left: 20px">You should be streaming ;)</p>
      <% end %>
    </div>
    <h2>Subscription</h2>
    <div class="row">
      <% if @subscribed_stores.count > 0 %>
          <% @subscribed_stores.each do |store| %>
              <%= render partial: 'stores/store_listing', locals: {store: store} %>
          <% end %>
      <% else %>
          <p style="margin-left: 20px">Check out the stores below!</p>
      <% end %>
    </div>
    <h2>Other Popular Stores</h2>
    <div class="row">
      <% if @other_stores.count > 0 %>
          <% @other_stores.each do |store| %>
              <%= render partial: 'stores/store_listing', locals: {store: store} %>
          <% end %>
      <% else %>
          <p>All stores have already been listed above!</p>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboard/_cat_dash.html.erb
<div id="cat_dash" role="tabpanel" class="tab-pane fade">
  <div class="container">
    <h2>Categories</h2>

    <div class="row">
      <% @categories.each do |category| %>
          <div class="col-md-4">
            <div class="content">
              <a href="<%= category_path(category) %>">
                <div class="grid">
                  <figure class="effect-apollo" style="max-height: 250px; height: 100vh;">
                    <%= image_tag category.avatar.url %>
                    <figcaption>
                      <h3><%= category.name %></h3>
                      <p>Go to category &rarr;</p>
                    </figcaption>
                  </figure>
                </div>
              </a>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboard/_seller_dash.html.erb
<div id="seller_dash" role="tabpanel" class="tab-pane fade">
  <div class="container">
    <div class="row">
      <div class="col-md-6">

        <h3>Start Streaming:</h3>
        <hr>
        <%= form_tag("/stores/#{current_user.store.slug}") do %>
            <div class="form">
              <%= hidden_field_tag :streaming_now, true %>
              <div class="form-group">
                <label><strong>Stream name:</strong></label>
                <input name="stream_name" class="form-control" required>
              </div>
              <div class="form-group">
                <label><strong>Choose products:</strong></label>
                <%= select_tag :product_ids, options_from_collection_for_select(@available_products, :id, :name), multiple: true, class: 'form-control', :required => true %>
              </div>
            </div>


            <div class="form-group">
              <%= submit_tag "GO LIVE!", class: 'btn btn-danger' %>
            </div>
            </div>
        <% end %>


        <div class="col-md-6">
          <h3>Seller Tasks</h3>
          <hr>
          <ul>
            <li>
              <%= link_to 'View my store', store_path(current_user.store) %>
            </li>
            <li>
              <%= link_to 'Edit my information', edit_user_registration_path(current_user) %>
            </li>
            <li>
              <%= link_to 'Add a new product', new_store_product_path(current_user.store) %>
            </li>
          </ul>
        </div>
        </div>
  </div>
</div>

app/views/dashboard/show.html.erb
<div class="container" style="padding-top: 43px">


  <div class="tab-content" style="margin-top: 30px">

    <!-- tabs -->
    <ul class="nav nav-tabs" role="tablist">

      <li class="nav-item">
        <a class="nav-link active" href="#buyer_dash" role="tab" data-toggle="tab"><%= @user.username %>'s Dashboard</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#cat_dash" role="tab" data-toggle="tab">Product Categories</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#seller_dash" role="tab" data-toggle="tab"><%= @user.username %>'s Storeboard</a>
      </li>
    </ul>

    <!-- tab contents -->
    <%= render 'buyer_dash' %>
    <%= render 'seller_dash' %>
    <%= render 'cat_dash' %>

  </div>
</div>