config/routes.rb
Rails.application.routes.draw do

  get 'videos/upload'

  resources :categories
  resources :carts, only: [:index]
  post '/payment' => 'carts#payment'
  resources :order_items, only: [:create, :update, :destroy]

  post '/rate' => 'rater#create', :as => 'rate'
  mount ActionCable.server => '/cable'

  root "home#index"

  post 'videos/upload'

  get ':username/follow_user', to: 'relationships#follow_user', as: :follow_user
  get ':username/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get '/dashboard' => 'dashboard#show', as: :dashboard

  post '/stores/:id' => 'stores#show', as: :start_streaming
  post '/stores/:id/end' => 'stores#show', as: :stop_streaming

  resources :stores, only: [:show, :edit, :update] do
    resources :products
  end

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users, only: [:create]
  get ':username' =>  'users#show'

  # DEVELOPMENT ONLY: sketches are html/css/js layouts with no logic yet,
  # the code can be reused elsewhere when backend ready
  get 'sketches/store' => 'sketches#store'
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, :presence => true
  validates_with AttachmentPresenceValidator, attributes: :avatar

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/follow.rb
class Follow < ApplicationRecord

  belongs_to :follower, foreign_key: 'follower_id', class_name: 'User'
  belongs_to :following, foreign_key: 'following_id', class_name: 'User'

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :store
  belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  has_many :order_items

  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

  private

  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:total] = subtotal
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end


  def total_price
    unit_price * quantity
  end

  private

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store
  belongs_to :category
  has_many :order_items

  validates :price, :presence => true
  validates :name, :presence => true
  validates :description, :presence => true
  validates :image, attachment_presence: true
  validates_with AttachmentPresenceValidator, attributes: :image

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user

  has_many :products, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_one :stream_instance

  extend FriendlyId
  friendly_id :name, use: :slugged

  ratyrate_rateable "quality"

  validates :name, presence: true, uniqueness: { message: "Username already in use" }
  validates :slug, presence: true, uniqueness: { message: "Username already in use" }

  #image stuff
  has_attached_file :cover_photo, styles: { large: "800x800>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :cover_photo, content_type: /\Aimage\/.*\z/

end

app/models/stream_instance.rb
class StreamInstance < ApplicationRecord
  belongs_to :store
end

app/models/user.rb
class User < ApplicationRecord

  has_one :store, dependent: :destroy
  has_many :messages, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,  :omniauthable, :omniauth_providers => [:facebook]

  # Config paperclip
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  # Config subscribe
  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following

  # Config ratyrate for rating
  ratyrate_rater

  # Actions
  after_create :generate_empty_store
  after_update :update_store_slug

  def follow(user_id)
    following_relationships.create(following_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.find_by(following_id: user_id).destroy
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.name.delete(' ')   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end


  private

    def generate_empty_store
      store = Store.create!(user_id: self.id, name: self.username)
      StreamInstance.create!(store_id: store.id)
    end

  def update_store_slug
    self.store.update(name: self.username, slug: nil)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def show
    @store = Store.friendly.find(params[:id])
    if @store == nil
      render file: "#{Rails.root}/public/404.html", layout: false
    end

    if params[:streaming_now]
      start_stream
    end

    if params[:end_stream]
      end_stream
    end

    @messages = @store.messages
    @streaming_products = Product.where(id: @store.stream_instance.product_ids)
    @products = @store.products - @streaming_products
    @order_item = current_order.order_items.new

  end

  def edit
    @store = Store.friendly.find(params[:id])
  end

  def start_stream
    @streamer_view = true
    @stream_name = params[:stream_name]
    streaming_product_ids = params[:product_ids]
    #@streaming_products = Product.where(id: streaming_product_ids)

    @store.update(streaming_now: true)
    clean_stream_instance
    @store.stream_instance.update(title: @stream_name, product_ids: streaming_product_ids)
  end

  def end_stream
    @store.update(streaming_now: false)
    clean_stream_instance
    respond_to do |format|
      format.html {
        flash[:success] = "Stream Ended"
        redirect_to dashboard_path
      }
      format.js {
        flash.now[:success] = "stream Ended"
      }
    end
  end

  def clean_stream_instance
    @store.stream_instance.update(title: nil, product_ids: [])
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sketches_helper.rb
module SketchesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/stores/_chat_tab.html.erb
<div id="chat" role="tabpanel" class="tab-pane fade <%= (@streamer_view == true || @store.streaming_now == true) ? 'show active' : '' %>">
  <div class="messages js-setup-store-chat" data-store-id="<%= @store.id %>">
    <p><strong>Welcome to Chat</strong></p>
  </div>

  <div class="chat-input<%= current_user ? '' : ' no-user' %>">
    <textarea rows="3" name="message_input" id="message-input" value="" placeholder="Type to chat"></textarea>
    <button id="message-send" >Send</button>
  </div>
</div>

app/views/stores/_info_tab.html.erb
<div id="profile" role="tabpanel" class="tab-pane fade <%= (@streamer_view || @store.streaming_now == true) ? '' : 'show active' %>">

  <div class="wrapper">
    <!-- Store Image -->
    <% if current_user %>
        <%= rating_for @store, "quality", star_path: '/images', star: 10, disable_after_rate: false, cancel_place: 'right' %>
    <% end %>
    <div>
      <%= image_tag @store.user.avatar.url(:medium) %>
    </div>

    <!-- Ratings -->
    <% if @store.average("quality") != nil %>
      <h5>Rating</h5> <%= @store.average("quality").avg%>/<%= @store.rates("quality").count %>
    <%end%>
    <hr>

    <!-- Basic Info -->
    <h4>About <%= @store.name %></h4>
    <p><%= @store.user.description || @store.description%></p>


    <!-- SUBSCRIBE / UNSUBSCRIBE LINKS -->
  </div>
</div>

app/views/stores/_inline-script.html.erb
<script>
    var videosContainer = document.getElementById('videos-container') || document.body;
    var setupNewBroadcast = document.getElementById('setup-new-broadcast');
    var roomsList = document.getElementById('rooms-list');
    var broadcastingOption = document.getElementById('broadcasting-option');
    var config = {
        openSocket: function (config) {
            // https://github.com/muaz-khan/WebRTC-Experiment/blob/master/Signaling.md
            // This method "openSocket" can be defined in HTML page
            // to use any signaling gateway either XHR-Long-Polling or SIP/XMPP or WebSockets/Socket.io
            // or WebSync/SignalR or existing implementations like signalmaster/peerserver or sockjs etc.

            var channel = config.channel || location.href.replace(/\/|:|#|%|\.|\[|\]/g, '');
            var socket = new Firebase('https://webrtc.firebaseIO.com/' + channel);
            socket.channel = channel;
            socket.on("child_added", function (data) {
                config.onmessage && config.onmessage(data.val());
            });
            socket.send = function (data) {
                this.push(data);
            };
            config.onopen && setTimeout(config.onopen, 1);
            socket.onDisconnect().remove();
            return socket;
        },
        onRemoteStream: function (htmlElement) {
            htmlElement.setAttribute('controls', true);
            document.getElementById("fake-video-placeholder").classList.add("display-none");
            videosContainer.insertBefore(htmlElement, videosContainer.firstChild);
            htmlElement.play();
        },
        onRoomFound: function (room) {
            var alreadyExist = document.querySelector('button[data-broadcaster="' + room.broadcaster + '"]');
            if (alreadyExist) return;

            if (typeof roomsList === 'undefined') roomsList = document.body;

            var tr = document.createElement('tr');
            tr.innerHTML = '<td><strong>' + room.roomName + '</strong> is live!</td>' +
                '<td><button class="join">Join</button></td>';
            roomsList.insertBefore(tr, roomsList.firstChild);

            var joinRoomButton = tr.querySelector('.join');
            joinRoomButton.setAttribute('data-broadcaster', room.broadcaster);
            joinRoomButton.setAttribute('data-roomToken', room.broadcaster);
            joinRoomButton.setAttribute('data-storeID', <%= store_id %>);
            joinRoomButton.onclick = function () {
                this.disabled = true;

                var broadcaster = this.getAttribute('data-broadcaster');
                var roomToken = this.getAttribute('data-roomToken');
                broadcastUI.joinRoom({
                    roomToken: roomToken,
                    joinUser: broadcaster
                });
                hideUnnecessaryStuff();
            };

            //tlock addition --> immediately click 'join' button for current room only
            <% if streaming_now %>
                document.querySelector('[data-storeid="<%= store_id %>"]').click();
                console.log('clicked store id: <%= store_id %> to join');
            <% end %>
        },
        onNewParticipant: function (numberOfViewers) {
            document.title = 'Viewers: ' + numberOfViewers;
            var viewersDiv = document.getElementById('viewers');
            var viewerCount = document.getElementById('viewer-count');
            viewersDiv.className = "fade show";
            viewerCount.textContent="Viewers: " + numberOfViewers;
        }
    };
    var audioRecorder, videoRecorder;
    if (setupNewBroadcast) setupNewBroadcast.onclick = setupNewBroadcastButtonClickHandler;

    function setupNewBroadcastButtonClickHandler() {
        document.getElementById('broadcast-name').disabled = true;
        document.getElementById('setup-new-broadcast').disabled = true;

        captureUserMedia(function () {
            var shared = 'video';
            broadcastUI.createRoom({
                roomName: (document.getElementById('broadcast-name') || {}).value || 'Anonymous',
                isAudio: shared === 'audio'
            });
        });
        hideUnnecessaryStuff();
    }


    function initRecorders(stream) {
        document.getElementById('stop-recording').disabled = false;
        audioRecorder = RecordRTC(stream, {
            recorderType: StereoAudioRecorder,
            bufferSize: 16384,  // mandatory: if 720p output is forced. otherwise: optional
            width: 1280, // optional---- to get 720p output
            height: 720
        });

        videoRecorder = RecordRTC(stream, {
            type: 'video', // Firefox doesn't accepts WhammyRecorder that's why we can't force it here
            frameInterval: 90
        });
        var flagInitSuccess = 0;
        videoRecorder.initRecorder(function () {
            callBackInitSuccess();
        });

        audioRecorder.initRecorder(function () {
            callBackInitSuccess();
        });

        function callBackInitSuccess(){
            if (flagInitSuccess == 2) {
                audioRecorder.startRecording();
                videoRecorder.startRecording();
            } else {
                flagInitSuccess += 1;
            }
        }


        document.getElementById('stop-recording').onclick = function () {

            var flag = 0;
            function saveVideo () {
                console.log(flag);
                flag+= 1;
                if (flag === 2) {
                    if (navigator.mozGetUserMedia === true) {
                        // Firefox!
                        var audioPlusVideoBlob = videoRecorder.blob;
                        alert('Audio+Video: ' + bytesToSize(audioPlusVideoBlob.size));
                        Upload_single_blob_to_server(audioPlusVideoBlob);
                        videoRecorder.save();
                        return;
                    }

                    var audioBlob = audioRecorder.blob;
                    var videoBlob = videoRecorder.blob;

                    videoRecorder.save();
                }
            }

            videoRecorder.stopRecording(function () {
//                saveVideo();
                console.log('stop Video');
                var file = new File([videoRecorder.getBlob()], 'video.webm', {
                    type: 'videos/webm'
                });

                var formData = new FormData();
                formData.append('file', file);

                $.ajax({
                    url: '/videos/upload',
                type: 'POST',
                data: formData,
                    processData: false,
                    contentType: false,
                    success: function(data) {
                    console.log(data);
                }
            })
            });

            audioRecorder.stopRecording(function () {
                saveVideo();
                console.log('stop Audio');

                // UPLOAD_both_blobs_to_server( audioBlob, videoBlob );
            });
            console.log(videoRecorder);

            this.disabled = true;
            document.getElementById('setup-new-broadcast').disabled = false;
            config.attachStream.getVideoTracks()[0].stop();
            config.attachStream.getAudioTracks()[0].stop();
        };

    }
    function captureUserMedia(callback) {
        var constraints = null;
        window.option = broadcastingOption ? broadcastingOption.value : '';

        if (option != 'Only Audio' && option != 'Screen' && DetectRTC.hasWebcam !== true) {
            console.log('DetectRTC library is unable to find webcam; maybe you denied webcam access once and it is still denied or maybe webcam device is not attached to your system or another app is using same webcam.');
        }

        var htmlElement = document.createElement(option === 'Only Audio' ? 'audio' : 'video');
        htmlElement.setAttribute('autoplay', true);
        htmlElement.setAttribute('controls', true);
        videosContainer.insertBefore(htmlElement, videosContainer.firstChild);

        var mediaConfig = {
            video: htmlElement,
            onsuccess: function (stream) {
                config.attachStream = stream;
                callback && callback();

                htmlElement.setAttribute('muted', true);
                initRecorders(stream);
            },
            onerror: function () {
                if (option === 'Only Audio') alert('unable to get access to your microphone');
                else if (option === 'Screen') {
                    if (location.protocol === 'http:') alert('Please test this WebRTC experiment on HTTPS.');
                    else alert('Screen capturing is either denied or not supported. Are you enabled flag: "Enable screen capture support in getUserMedia"?');
                } else alert('unable to get access to your webcam');
            }
        };
        if (constraints) mediaConfig.constraints = constraints;
        getUserMedia(mediaConfig);
    }

    var broadcastUI = broadcast(config);

    function hideUnnecessaryStuff() {
        var visibleElements = document.getElementsByClassName('visible'),
            length = visibleElements.length;
        for (var i = 0; i < length; i++) {
            visibleElements[i].style.display = 'none';
        }
    }
</script>

app/views/stores/_side_panel.html.erb
<div class="panel open">

  <!-- Tab panes -->
  <div class="tab-content">

    <!-- tabs -->
    <ul class="nav nav-tabs" role="tablist">

      <!-- toggle -->
      <div class="panel-toggle">
        <button><i class="icon-collapse"></i></button>
      </div>

      <li class="nav-item">
        <a class="nav-link <%= (@streamer_view == true || @store.streaming_now == true) ? 'active' : '' %>" href="#chat" role="tab" data-toggle="tab">Chat</a>
      </li>
      <li class="nav-item">
        <a class="nav-link <%= (@streamer_view == true || @store.streaming_now == true) ? '' : 'active' %>" href="#profile" role="tab" data-toggle="tab">About Seller</a>
      </li>
    </ul>

    <%= render 'chat_tab' %>
    <%= render 'info_tab' %>

  </div>
</div>

app/views/stores/_store_listing.html.erb
<div class="col-md-4">
  <div class="content">
    <a href="<%= store_path(store) %>">
      <div class="grid">
        <figure class="effect-apollo" style="max-height: 250px; height: 100vh;">
          <%= image_tag store.cover_photo(:large) %>
          <figcaption>
            <h3><%= store.name %></h3>
            <p>Go to store &rarr;</p>
          </figcaption>
        </figure>
      </div>
    </a>
  </div>
</div>

app/views/stores/show.html.erb
<!-- PANEL -->
<script src="https://cdn.webrtc-experiment.com/RecordRTC.js"></script> <!-- audio/video recording -->
<%= render 'side_panel' %>

<!-- MAIN -->
<div id="main">
  <% if @store.streaming_now == true %>
      <h3 id="store-headline"><% if current_user && current_user.id != @store.user.id %>
            <% if current_user_is_following(current_user.id, @store.user.id)%>
                <%= link_to "Unsubscribe", unfollow_user_path(@store.user.username)%>
            <% else %>
                <%= link_to "Subscribe", follow_user_path(@store.user.username)%>
            <% end %>
            <% end %> <%= @store.name %><span class="message"> is live: <%= @store.stream_instance.title %></span></h3>
  <% else %>
      <h3 id="store-headline"> <% if current_user && current_user.id != @store.user.id %>
            <% if current_user_is_following(current_user.id, @store.user.id)%>
                <%= link_to "Unsubscribe", unfollow_user_path(@store.user.username), class: 'btn btn-primary'%>
            <% else %>
                <%= link_to "Subscribe", follow_user_path(@store.user.username), class: 'btn btn-primary'%>
            <% end %>
            <% end %><%= @store.name %><span class="message">  is offline</span></h3>
  <% end %>
  <section class="theater">

    <div id="stream" style="background-image: url(<%= @store.cover_photo.url(:original) %>)">

      <!-- Overlay -->
      <% if @store.streaming_now %>
        <div class="overlay fade show">
          <div class="wrapper">
            <div class="spinner"></div>
          </div>
        </div>
      <% end %>

      <!-- Kill Button -->
      <% if @streamer_view %>
          <button id="stop-recording" class="btn btn-danger">End Stream</button>
          <!-- Hidden Form -->
          <%= form_tag("/stores/#{current_user.store.slug}/end", remote: true, style: "display: none") do %>
            <%= hidden_field_tag :end_stream, true %>
            <%= submit_tag "End Stream", id: "end-stream-submit" %>
          <% end %>
      <% end %>

      <!-- Viewer Count -->
      <div id="viewers" class="fade hide">
        <span class="svg-wrapper">
          <svg xmlns="http://www.w3.org/2000/svg"><circle cx="5" cy="5" r="5" fill="red"></circle></svg>
          <span id="viewer-count">Viewers: -1</span>
        </span>
      </div>

      <% if @streamer_view %>
          <section style="display: none;">
            <input type="text" id="broadcast-name" value="<%= @stream_name %>">
            <button id="setup-new-broadcast" class="setup">Setup New Broadcast</button>
          </section>
      <% else %>
          <!-- list of all available broadcasting rooms -->
          <table style="display: none; width: 100%;" id="rooms-list"></table>
      <% end %>

      <!-- placeholder to make sizing work with many dynamic events on page -->
      <%= image_tag "video_placeholder.png", id: 'fake-video-placeholder', class: @streamer_view ? "fake-video display-none" : "fake-video" %>

      <!-- local/remote videos container -->
      <div id="videos-container"></div>

      <%= render partial: 'inline-script', locals: { store_id: @store.id, streamer_view: @streamer_view, streaming_now: @store.streaming_now } %>

    </div>

  </section>

  <% if @store.streaming_now == true %>
    <section id="streaming-products" class="products">
      <h3>Products in this stream</h3>
      <hr>
      <div class="container row">
      <% @streaming_products.each do |product| %>
        <%= render partial: 'products/product', order_item: @order_item, locals: {product: product}, class: 'col-md-6' %>
      <% end %>
      </div>
    </section>
  <% end %>

  <section id="main-products" class="products">

    <% if @store.streaming_now == true %>
        <h3 id="other-products-headline">Other popular products by seller</h3>
    <% else %>
        <h3>Products:</h3>
    <% end %>

    <hr>
    <div class="container-fluid">
      <div class="row">
        <%= render @products %>
      </div>
    </div>
  </section>
</div>