config/routes.rb
Rails.application.routes.draw do

  get 'videos/upload'

  resources :categories
  resources :carts, only: [:index]
  post '/payment' => 'carts#payment'
  resources :order_items, only: [:create, :update, :destroy]

  post '/rate' => 'rater#create', :as => 'rate'
  mount ActionCable.server => '/cable'

  root "home#index"

  post 'videos/upload'

  get ':username/follow_user', to: 'relationships#follow_user', as: :follow_user
  get ':username/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get '/dashboard' => 'dashboard#show', as: :dashboard

  post '/stores/:id' => 'stores#show', as: :start_streaming
  post '/stores/:id/end' => 'stores#show', as: :stop_streaming

  resources :stores, only: [:show, :edit, :update] do
    resources :products
  end

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users, only: [:create]
  get ':username' =>  'users#show'

  # DEVELOPMENT ONLY: sketches are html/css/js layouts with no logic yet,
  # the code can be reused elsewhere when backend ready
  get 'sketches/store' => 'sketches#store'
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, :presence => true
  validates_with AttachmentPresenceValidator, attributes: :avatar

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/follow.rb
class Follow < ApplicationRecord

  belongs_to :follower, foreign_key: 'follower_id', class_name: 'User'
  belongs_to :following, foreign_key: 'following_id', class_name: 'User'

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :store
  belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  has_many :order_items

  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

  private

  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:total] = subtotal
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end


  def total_price
    unit_price * quantity
  end

  private

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store
  belongs_to :category
  has_many :order_items

  validates :price, :presence => true
  validates :name, :presence => true
  validates :description, :presence => true
  validates :image, attachment_presence: true
  validates_with AttachmentPresenceValidator, attributes: :image

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user

  has_many :products, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_one :stream_instance

  extend FriendlyId
  friendly_id :name, use: :slugged

  ratyrate_rateable "quality"

  validates :name, presence: true, uniqueness: { message: "Username already in use" }
  validates :slug, presence: true, uniqueness: { message: "Username already in use" }

  #image stuff
  has_attached_file :cover_photo, styles: { large: "800x800>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :cover_photo, content_type: /\Aimage\/.*\z/

end

app/models/stream_instance.rb
class StreamInstance < ApplicationRecord
  belongs_to :store
end

app/models/user.rb
class User < ApplicationRecord

  has_one :store, dependent: :destroy
  has_many :messages, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,  :omniauthable, :omniauth_providers => [:facebook]

  # Config paperclip
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  # Config subscribe
  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following

  # Config ratyrate for rating
  ratyrate_rater

  # Actions
  after_create :generate_empty_store
  after_update :update_store_slug

  def follow(user_id)
    following_relationships.create(following_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.find_by(following_id: user_id).destroy
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.name.delete(' ')   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end


  private

    def generate_empty_store
      store = Store.create!(user_id: self.id, name: self.username)
      StreamInstance.create!(store_id: store.id)
    end

  def update_store_slug
    self.store.update(name: self.username, slug: nil)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/shared/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )",  carts_path, class: "btn btn-link" %>

app/views/shared/_navbar.html.erb
<nav class="navbar fixed-top navbar-toggleable-sm navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <a class="navbar-brand mx-auto text-center" href="<%= root_path %>">
      <%= image_tag 'logo-black@2x.png', style: 'width: 60%' %>
      <div id="trapezoid"></div>
    </a>


    <ul class="navbar-nav ml-auto">
      <% if current_user #logged in %>
        <li class="nav-item">
          <a class="nav-link" href="<%= dashboard_path %>">Dashboard</a>
        </li>

        <!-- <li class="nav-item dropdown">
          <a class="nav-link" id="myStoreDropdown" data-target="#" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">My Store <span class="dropdown-arrow">&#9660;</span></a>
          <ul class="dropdown-menu" aria-labelledby="myStoreDropdown">
            <li><%= link_to 'View', store_path(current_user.store), class: "dropdown-item" %></li>
            <li><%= link_to 'Edit', edit_user_registration_path(current_user), class: "dropdown-item" %></li>
            <li><%= link_to 'Add Product', new_store_product_path(current_user.store), class: "dropdown-item" %></li>
            <li><%= link_to 'Start Streaming', dashboard_path, class: "dropdown-item" %></li>
          </ul>
        </li> -->

        <li class="nav-item">
          <%= link_to "Cart",  carts_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <span class="nav-link"> | </span>
        </li>

        <li class="nav-item">
          <%= link_to "Log Out", destroy_user_session_path, method: 'delete', class: 'nav-link' %>
        </li>
        <% else #Logged out %>

          <li class="nav-item">
            <a class="nav-link" href="<%= new_user_session_path %>">Login</a>
          </li>
          <li class="nav-item">
            <span class="nav-link"> | </span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_user_registration_path %>">Register</a>
          </li>

        <% end %>

      </ul>
    </div>
  </nav>