config/routes.rb
Rails.application.routes.draw do

  get 'videos/upload'

  resources :categories
  resources :carts, only: [:index]
  post '/payment' => 'carts#payment'
  resources :order_items, only: [:create, :update, :destroy]

  post '/rate' => 'rater#create', :as => 'rate'
  mount ActionCable.server => '/cable'

  root "home#index"

  post 'videos/upload'

  get ':username/follow_user', to: 'relationships#follow_user', as: :follow_user
  get ':username/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get '/dashboard' => 'dashboard#show', as: :dashboard

  post '/stores/:id' => 'stores#show', as: :start_streaming
  post '/stores/:id/end' => 'stores#show', as: :stop_streaming

  resources :stores, only: [:show, :edit, :update] do
    resources :products
  end

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users, only: [:create]
  get ':username' =>  'users#show'

  # DEVELOPMENT ONLY: sketches are html/css/js layouts with no logic yet,
  # the code can be reused elsewhere when backend ready
  get 'sketches/store' => 'sketches#store'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, :presence => true
  validates_with AttachmentPresenceValidator, attributes: :avatar

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @order_item = current_order.order_items.new
    @store = Store.friendly.find(params[:id])
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :avatar)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
    <% if category.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

          <ul>
            <% category.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :Image %>
      <%= form_for @category, url: users_path, html: { multipart: true } do |form| %>
          <%= form.file_field :avatar %>
      <% end %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="container">
  <h1>Categories</h1>

  <div class="row">
    <% @categories.each do |category| %>
        <div class="col-md-4">
          <div class="content">
            <a href="<%= category_path(category) %>">
              <div class="grid">
                <figure class="effect-apollo" style="max-height: 250px; height: 100vh;">
                  <%= image_tag category.avatar.url %>
                  <figcaption>
                    <h3><%= category.name %></h3>
                    <p>Go to category &rarr;</p>
                  </figcaption>
                </figure>
              </div>
            </a>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container" style="padding-top: 50px">
  <h2><%= @category.name %></h2>
  <div class="row">
    <% Product.where(category_id: @category.id).each do |product| %>
        <div class="col-md-4">
          <div data-target="#myModal-<%= product.id %>" data-toggle="modal">
            <div class="content">
              <div class="grid">
                <figure class="effect-apollo" style="max-height: 250px; height: 100vh;">
                  <%= image_tag product.image.url(:original), class: 'card-img-top' %>
                  <figcaption>
                    <h3><%= product.name %></h3>
                    <p>See More &rarr;</p>
                  </figcaption>
                </figure>
              </div>
            </div>


            <div id="myModal-<%= product.id %>" class="modal">

              <!-- Modal content -->
              <div class="modal-content">
                <div class="row">
                  <div class="col-md-6">
                    <%= image_tag product.image.url(:original),  :style => "max-height: 476px" %>
                  </div>
                  <div class="col-md-6 text-left">
                    <h3><%= product.name %></h3>
                    <hr>
                    <p><%= product.description %></p>
                    <p><%= product.price %> VND</p>
                    <%= form_for @order_item do |f| %>
                        <%= f.hidden_field :quantity, value: 1, min: 1, class: 'form-control' %>
                        <%= f.hidden_field :unit_price, value: product.price %>
                        <%= f.hidden_field :product_id, value: product.id %>
                        <%= f.submit "Buy now", class: "btn CL-button" %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
    <% end %>
    </div>
  </div>
</div>
</div>